declare const styles: {
  readonly "uranus-comment-editor-container": string;
  readonly "uranus-comment-container": string;
  readonly "uranus-avatar-box": string;
  readonly "comment-avatar": string;
  readonly "uranus-form-box": string;
  readonly "input-box": string;
  readonly "uranus-comment-editor": string;
  readonly "uranus-mention": string;
  readonly "mention-box": string;
  readonly "mention-item": string;
  readonly "action-box": string;
  readonly "emoji": string;
  readonly "emoji-box": string;
  readonly "emoji-container": string;
  readonly "emoji-dots": string;
  readonly "slick-active": string;
  readonly "slick-dots-bottom": string;
  readonly "emoji-content": string;
  readonly "emoji-picker": string;
  readonly "emojis": string;
  readonly "item": string;
  readonly "emoji-element": string;
  readonly "uranus-emoji": string;
  readonly "submit": string;
  readonly "comment-list": string;
  readonly "sub-comment-list": string;
  readonly "comment-item": string;
  readonly "meta-box": string;
  readonly "reply-stat": string;
  readonly "time": string;
  readonly "delete": string;
};
export = styles;

