declare const styles: {
  readonly "uranus_comment_editor_container": string;
  readonly "uranus_comment_container": string;
  readonly "uranus_avatar_box": string;
  readonly "comment_avatar": string;
  readonly "uranus_form_box": string;
  readonly "input_box": string;
  readonly "uranus_comment_editor": string;
  readonly "mention_box": string;
  readonly "mention_item": string;
  readonly "action_box": string;
  readonly "emoji": string;
  readonly "emoji_box": string;
  readonly "emoji_container": string;
  readonly "emoji_dots": string;
  readonly "slick_active": string;
  readonly "slick_dots_bottom": string;
  readonly "emoji_content": string;
  readonly "emoji_picker": string;
  readonly "emojis": string;
  readonly "item": string;
  readonly "submit": string;
  readonly "comment_list": string;
  readonly "sub_comment_list": string;
  readonly "comment_item": string;
  readonly "meta_box": string;
  readonly "reply_stat": string;
  readonly "time": string;
  readonly "delete": string;
};
export = styles;

