name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USNER }} registry.cn-hongkong.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag registry.cn-hongkong.aliyuncs.com/houhou/uranus-frontend-hk:${{ github.sha }}
          docker push registry.cn-hongkong.aliyuncs.com/houhou/uranus-frontend-hk:${{ github.sha }}
      # k8s部署
      - run: |
          sed -i 's/{TAG}/${{ github.sha }}/g' .deploy/deployment.yml
      - name: k8s deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.14.1
          command: apply -f .deploy/deployment.yml
      - name: k8s service
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.14.1
          command: apply -f .deploy/service.yml
      - name: deployment status
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: v1.14.1
          command: '"rollout status deployment/uranus-frontend"'
